### 

POST https://order-mcp-74afyau24q-uc.a.run.app/mcp HTTP/1.1
Accept: application/json, text/event-stream

{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "tools/list",
  "params": {}
}


### 

POST http://127.0.0.1:8000/api/chat HTTP/1.1
Accept: : application/json

{
  "message": "Do you have any wireless keyboards in stock?"
}


### 

GET http://127.0.0.1:8000/health HTTP/1.1
